
server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://hkwiusifmynnrq:7067806bcfff9d11fe0aef63827b6f656fe65782ace15663c3f08034826ede35@ec2-52-86-25-51.compute-1.amazonaws.com:5432/d894r8su9horj0
    username: hkwiusifmynnrq
    password: 7067806bcfff9d11fe0aef63827b6f656fe65782ace15663c3f08034826ede35

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto Criado no Bootcamp Santander - DIO
